version: '3.8'

services:
  laravel:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./database/database.sqlite:/app/database/database.sqlite
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /app/database/database.sqlite
    command: >
      sh -c "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"
